### ISSUE TITLE
Please add this adapter to the repository

### ISSUE THREAD

**Issue by ldittmar81** [hombach/ioBroker.chargemaster#164]
It would be really greate to see this adapter on ioBroker. Please add it to the repository. You can see how to do this here: https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-latest-repository

Thanks for it :-)

**Comment by hombach** [comment]
You're welcome - but it is still an development version.... do you it is worth publishing in latest repo right now?
Good point would be possible help/ideas/testing etc....

**Comment by ldittmar81** [comment]
I have a wallbox, but I'm still waiting for my PV. You can create a thread for testing here https://forum.iobroker.net/category/91/tester - I think a lot of users would be very happy with such an adapter. Me too, but I mus to wait till my PV is installed :-)

**Comment by hombach** [comment]
OK... pull request for registering the adapter is filed

**Comment by hombach** [comment]
pull request cancelled I need to pull another adapter first....
 "chargemaster": {
    "meta": "https://raw.githubusercontent.com/hombach/ioBroker.chargemaster/master/io-package.json",
    "icon": "https://raw.githubusercontent.com/hombach/ioBroker.chargemaster/master/admin/chargemaster.png",
    "type": "vehicle"
  },

**Comment by hombach** [comment]
filed new PR

**Comment by hombach** [comment]
adapter is part of "latest" repo
